/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class PolygonShape extends Shape {
	private transient long swigCPtr;

	//Aggiunto da Davide
	public float halfX, halfY;
	@Override
	public String toString(){
		return type.name()+": "+halfX+" x "+halfY;
	}
	//-D

	protected PolygonShape(long cPtr, boolean cMemoryOwn) {
		super(liquidfunJNI.PolygonShape_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
		this.type=Type.POLYGON;   //D
	}

	public PolygonShape() {
		this(liquidfunJNI.new_PolygonShape(), true);
	}

	public void setAsBox(float hx, float hy) {
		liquidfunJNI.PolygonShape_setAsBox__SWIG_0(swigCPtr, this, hx, hy);
		//D
		this.type=Type.BOX;
		this.halfX=hx;
		this.halfY=hy;
		//-D
	}

	public void setAsBox(float hx, float hy, float centerX, float centerY, float angle) {
		liquidfunJNI.PolygonShape_setAsBox__SWIG_1(swigCPtr, this, hx, hy, centerX, centerY, angle);
		//D
		this.type=Type.BOX;
		this.halfX=hx;
		this.halfY=hy;
		//-D
	}

	protected static long getCPtr(PolygonShape obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				liquidfunJNI.delete_PolygonShape(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public void setCentroid(float x, float y) {
		liquidfunJNI.PolygonShape_setCentroid(swigCPtr, this, x, y);
	}

}
